language: go
sudo: false

install:
  - GOPATH=$TRAVIS_BUILD_DIR
  - go get "github.com/stretchr/testify/assert"

script:
  - go test arithmetic stuff -json > testdata.json
  - cat testdata.json

after_script:
  - curl -s https://raw.githubusercontent.com/report-ci/scripts/master/upload.py | python  - --preset posix