language: go
sudo: false

install:
  - GOPATH=$TRAVIS_BUILD_DIR
  - go get "github.com/stretchr/testify/assert"

script:
  - go test arithmetic -json > testdata.json

after_script:
  - python <(curl -s https://raw.githubusercontent.com/report-ci/scripts/master/upload.py)